language: rust

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-5

os:
  - linux

rust:
  - stable

env:
  global:
    - CARGO_TARGET_DIR=/tmp/bindgen
  matrix:
    - LLVM_VERSION="3.8.1" BINDGEN_JOB="test"         BINDGEN_PROFILE=
    - LLVM_VERSION="3.8.1" BINDGEN_JOB="test"         BINDGEN_PROFILE="--release"
    - LLVM_VERSION="3.8.1" BINDGEN_JOB="integration"  BINDGEN_PROFILE=
    - LLVM_VERSION="3.8.1" BINDGEN_JOB="integration"  BINDGEN_PROFILE="--release"
    - LLVM_VERSION="3.9.0" BINDGEN_JOB="test"         BINDGEN_PROFILE=
    - LLVM_VERSION="3.9.0" BINDGEN_JOB="test"         BINDGEN_PROFILE="--release"
    - LLVM_VERSION="3.9.0" BINDGEN_JOB="integration"  BINDGEN_PROFILE=
    - LLVM_VERSION="3.9.0" BINDGEN_JOB="integration"  BINDGEN_PROFILE="--release"
    - LLVM_VERSION="4.0.0" BINDGEN_JOB="test"         BINDGEN_PROFILE=
    - LLVM_VERSION="4.0.0" BINDGEN_JOB="test"         BINDGEN_PROFILE="--release"
    - LLVM_VERSION="4.0.0" BINDGEN_JOB="test"         BINDGEN_PROFILE=            BINDGEN_FEATURES="testing_only_extra_assertions"
    - LLVM_VERSION="4.0.0" BINDGEN_JOB="test"         BINDGEN_PROFILE="--release" BINDGEN_FEATURES="testing_only_extra_assertions"
    - LLVM_VERSION="4.0.0" BINDGEN_JOB="integration"  BINDGEN_PROFILE=
    - LLVM_VERSION="4.0.0" BINDGEN_JOB="integration"  BINDGEN_PROFILE="--release"
    - LLVM_VERSION="4.0.0" BINDGEN_JOB="expectations" BINDGEN_PROFILE=
    - LLVM_VERSION="4.0.0" BINDGEN_JOB="expectations" BINDGEN_PROFILE="--release"
    - LLVM_VERSION="4.0.0" BINDGEN_JOB="misc"
    - LLVM_VERSION="4.0.0" BINDGEN_JOB="quickchecking"

matrix:
  fast_finish: true
  allow_failures:
    - env: LLVM_VERSION=4.0.0 BINDGEN_JOB=rustfmt

cache:
  directories:
    - $HOME/.cargo
    - $HOME/.llvm-builds

before_install: . ./ci/before_install.sh

script:
  - BINDGEN_JOB="$BINDGEN_JOB" BINDGEN_PROFILE="$BINDGEN_PROFILE" BINDGEN_FEATURES="$BINDGEN_FEATURES" ./ci/script.sh

after_success:
  - test "$TRAVIS_PULL_REQUEST" == "false" &&
    test "$TRAVIS_BRANCH" == "master" &&
    test "$BINDGEN_JOB" == "misc" &&
    ./ci/deploy-book.sh

notifications:
  webhooks: http://build.servo.org:54856/travis
