language: rust
addons:
    apt:
      sources:
        - llvm-toolchain-precise
        - llvm-toolchain-precise-3.5
        - llvm-toolchain-precise-3.8
        - ubuntu-toolchain-r-test
      packages:
        - libclang-3.5-dev
        - llvm-3.5-dev
        - libclang-3.8-dev
        - llvm-3.8-dev
env:
  - LLVM_VERSION=3.5
  - LLVM_VERSION=3.8
rust:
  - stable
  - beta
  - nightly
os:
  - osx
  - linux
matrix:
  allow_failures:
    - rust: nightly
  include:
    - os: linux
      env: LLVM_VERSION=3.5
      rust: stable
      script: cargo build --features static --verbose
    - os: osx
      env: LLVM_VERSION=devtools
      rust: stable
    - os: linux
      env: LLVM_VERSION=3.5
      rust: nightly
      script: cargo build --features clippy

notifications:
  webhooks: http://build.servo.org:54856/travis

cache: cargo

before_install:
  -
    if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
      if [ "${LLVM_VERSION}" != "devtools" ]; then
        brew update >/dev/null;
        brew install llvm3${LLVM_VERSION#3.};
      fi
    fi

before_script:
  -
    if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
      export LIBCLANG_PATH=/usr/lib/llvm-${LLVM_VERSION}/lib;
    elif [ "${TRAVIS_OS_NAME}" = "osx" ]; then
      if [ "${LLVM_VERSION}" = "devtools" ]; then
        export LIBCLANG_PATH=/Library/Developer/CommandLineTools/usr/lib;
      else
        export LIBCLANG_PATH=`brew --prefix llvm3${LLVM_VERSION#3.}`/lib/llvm-${LLVM_VERSION}/lib;
      fi
    fi
  - echo $LIBCLANG_PATH
