[package]
name = "bindgen-tests"
edition = "2018"
version = "0.1.0"
publish = false

[dev-dependencies]
bindgen = { path = "../bindgen", features = ["__cli", "experimental"] }
clap = { version = "4", features = ["derive"] }
clap_complete = "4"
shlex = "1"
prettyplease = { version = "0.2.7", features = ["verbatim"] }
syn = { version = "2.0" }
tempfile = "3"
similar = { version = "2.2.1", features = ["inline"] }
owo-colors = "3.5.0"

[features]
logging = ["bindgen/logging"]
static = ["bindgen/static"]
runtime = ["bindgen/runtime"]
which-rustfmt = ["bindgen/which-rustfmt"]

__testing_only_extra_assertions = ["bindgen/__testing_only_extra_assertions"]
__testing_only_libclang_9 = ["bindgen/__testing_only_libclang_9"]
__testing_only_libclang_16 = ["bindgen/__testing_only_libclang_16"]
