[package]
name = "bindgen-tests"
edition = "2018"
version = "0.1.0"
publish = false

[dev-dependencies]
bindgen = { path = "../bindgen" }
diff = "0.1"
shlex = "1"
clap = "3"
tempfile = "3"

[features]
logging = ["bindgen/logging"]
static = ["bindgen/static"]
runtime = ["bindgen/runtime"]
which-rustfmt = ["bindgen/which-rustfmt"]

testing_only_docs = ["bindgen/testing_only_docs"]
testing_only_extra_assertions = ["bindgen/testing_only_extra_assertions"]
testing_only_libclang_9 = ["bindgen/testing_only_libclang_9"]
testing_only_libclang_5 = ["bindgen/testing_only_libclang_5"]
